apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ihub-iit-assignment-3
  labels:
    app: deployment-ihub-iit-assignment-3
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deployment-ihub-iit-assignment-3
  template:
    metadata:
      labels:
        app: deployment-ihub-iit-assignment-3
    spec:
      containers:
      - name: deployment-ihub-iit-assignment-3
        image: dockerkumargaurav/ihub-iit-assignment-3
        ports:
        - containerPort: 8088
