apiVersion: v1
kind: Service
metadata:
  name: app-nodeport-svc
spec:
  selector:
    app: deployment-ihub-iit-assignment-3
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30080
